dic = {
    'product_url': 'https://www.amazon.com/BABESIDE-Realistic-Accessories-Pretend-Collection/dp/B0CY4X37RD/ref=sr_1_1?crid=YX02N6RBFVQ8&dib=eyJ2IjoiMSJ9.W5i03qIegSFoDjEH88lLUjIfKwIj1nL4sNZ-bsRdWXxGkCVr-Ijl57vaN7XB5AeA3Qj9HM0_TvwwjyH09CxkuMFrx4Y8U95HQz-8iDm7hW__MjLT3p5E19Jg40gjkDTZMC2s6w203lqBnQEoPvnWv3gVz49ppFEcwLVk0odLhtwX4uFpOywPOe41G2Gj4d5wItlfMzxdmKZyNIQDqtDPujeIbgojQXGV3dKyE0I7_GfpwTJH0OaCyGyxRdn0UI-hlxsjO65zll-1PnDVvLzVxetMPm0J4Ufj9EReePW18BA.eoHCtji11ustwwAvEY6WHzR51zpVv0WjPVYO9sPfGIk&dib_tag=se&keywords=dolls&qid=1777029196&sprefix=dolls%2Caps%2C313&sr=8-1',
    'title': 'BABESIDE Baby Dolls, 17inch Large Realistic Cute Soft Body Baby Doll Real Life Baby Dolls with Accessories for 3+ Year Old Girls Gifts, Pretend Play, Collection',
    'asin': 'B0CY4X37RD', 'price': '$23.98', 'rating': '4.6', 'review_count': '(4,080)', 'category_path': '',
    'category_name': '', 'department': '', 'subcategory': '', 'attributes': {}, 'bullet_points': [
        'More Life-like Realism: Experience the joy of cuddling with a doll that feels just like the real thing! Our 17-inch big baby doll is easier to hug and hold. With hand-rooted eyelashes, delicate baby-like fingernails, and realistic folds on its tiny hands and feet, the rosy cheeks add to its charm, making it a delightful addition to any doll collection',
        'Irresistibly Cute and Soft: With its endearing smile and poseable limbs, this baby doll is guaranteed to capture your heart. Her head is made of premium vinyl materials with a cloth body and limbs, soft to the touch, ensuring hours of cuddly fun for your little one. Plus, its durable construction means it can withstand all the love and playtime your child can give',
        "Inspiring Imagination and Play: Whether your child enjoys pretend play, role-playing as a parent, or simply having a buddy to accompany them during the day, this new born baby doll fits the bill. It's also great for stimulating children's imagination and fostering creativity. Beyond playtime, it's an ideal collectible for doll enthusiasts of age 3+",
        'Exciting Accessories for Interactive Fun: Our toy baby doll comes with an array of accessories to enhance the play experience. It includes a birth certificate, and a cute outfit to keep things fresh and engaging, add layers of fun(not included bunny rattle)',
        "Perfect Gift for Every Occasion: Whether it's a birthday, Christmas or special holiday, our cute baby doll makes the perfect gift for children! Plus, it's made with safety in mind, using non-toxic materials, giving you peace of mind as your child plays and explores."],
    'description': "More Life-like Realism: Experience the joy of cuddling with a doll that feels just like the real thing! Our 17-inch big baby doll is easier to hug and hold. With hand-rooted eyelashes, delicate baby-like fingernails, and realistic folds on its tiny hands and feet, the rosy cheeks add to its charm, making it a delightful addition to any doll collectionIrresistibly Cute and Soft: With its endearing smile and poseable limbs, this baby doll is guaranteed to capture your heart. Her head is made of premium vinyl materials with a cloth body and limbs, soft to the touch, ensuring hours of cuddly fun for your little one. Plus, its durable construction means it can withstand all the love and playtime your child can giveInspiring Imagination and Play: Whether your child enjoys pretend play, role-playing as a parent, or simply having a buddy to accompany them during the day, this new born baby doll fits the bill. It's also great for stimulating children's imagination and fostering creativity. Beyond playtime, it's an ideal collectible for doll enthusiasts of age 3+Exciting Accessories for Interactive Fun: Our toy baby doll comes with an array of accessories to enhance the play experience. It includes a birth certificate, and a cute outfit to keep things fresh and engaging, add layers of fun(not included bunny rattle)Perfect Gift for Every Occasion: Whether it's a birthday, Christmas or special holiday, our cute baby doll makes the perfect gift for children! Plus, it's made with safety in mind, using non-toxic materials, giving you peace of mind as your child plays and explores.›See more product details",
    'reviews': [], 'product_more_datas': {'基础信息': {
        '产品名称': 'BABESIDE Baby Dolls, 17inch Large Realistic Cute Soft Body Baby Doll Real Life Baby Dolls with Accessories for 3+ Year Old Girls Gifts, Pretend Play, Collection',
        '当前价格': '$23.98', 'ASIN': 'B0CY4X37RD', '品牌': 'BABESIDE'},
        '物理规格': {'尺寸': '17"L x 7"W x 5"H', '大小': '17 inches',
                     '单位数量': '1.0 Count', '是否需要组装': 'No'},
        '外观与设计': {'动物主题': 'Unicorn', '色彩': 'A Pink', '主题': 'Fantasy',
                       '风格': 'Modern',
                       '适合场景': 'Baby Shower, Birthday, Christmas, Party, Thanksgiving'},
        '制造信息': {'厂商型号': 'RSG004NIWA-YJ', '建议最小年龄': '36.0',
                     '材质': 'Cotton, Vinyl', '包含组件': 'doll & accessories'},
        '市场表现': {'评分': '4.6', '评论数': '(4,080)',
                     '销售排名': '#1,578 in Toys & Games (See Top 100 in Toys & Games)#11 inDolls'}}}
