# -*- coding: utf-8 -*-
"""Schemas for dynamic product usage-scene generation."""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, TypedDict

from pydantic import BaseModel, Field


ProductCategory = Literal[
    "tool",
    "hardware",
    "mechanical",
    "electronics",
    "home_goods",
    "kitchenware",
    "apparel",
    "soft_goods",
    "other",
]

PreserveLevel = Literal["pixel", "strict", "creative"]


class ProductAnalysis(BaseModel):
    """LLM analysis of the uploaded product image."""

    product_name: str = Field(description="商品名称，例如 adjustable wrench")
    category: ProductCategory = Field(description="商品类别")
    preserve_level: PreserveLevel = Field(description="保真等级")
    key_structure_points: List[str] = Field(default_factory=list, description="必须保持不变的结构点")
    risk_points: List[str] = Field(default_factory=list, description="容易被生成模型改错的区域")


class ScenePlan(BaseModel):
    """
    A dynamic scene + layout plan generated by the LLM.

    用户不需要手动提供 target_width_ratio / center_x_ratio / center_y_ratio / rotation_degrees。
    这些由大模型根据商品和场景自动规划，再由程序执行几何变换和合成。
    """

    name: str = Field(description="场景任务名，例如 workbench_repair_scene")
    scene_prompt: str = Field(description="用于生成背景场景的 prompt")
    usage_context: str = Field(description="商品在该场景中的自然出现方式")

    target_width_ratio: float = Field(description="商品目标宽度占画布宽度比例，建议 0.25~0.90")
    center_x_ratio: float = Field(description="商品中心点 x 比例，0~1")
    center_y_ratio: float = Field(description="商品中心点 y 比例，0~1")
    rotation_degrees: float = Field(description="商品旋转角度，工具类建议 -25~25 度")

    depth_layer: Literal["foreground", "midground", "background"] = "foreground"
    visual_role: Literal["hero", "primary", "supporting"] = "primary"
    shadow_strength: Literal["soft", "medium", "strong"] = "medium"
    preserve_level: PreserveLevel = "pixel"


class MultiScenePlan(BaseModel):
    """LLM planning result: product analysis + multiple scene plans."""

    product: ProductAnalysis
    scenes: List[ScenePlan]


class ImageWorkflowState(TypedDict, total=False):
    """
    LangGraph state schema.

    它是每次 graph.invoke() 内部传递的工作流状态，不是全局变量。
    """

    user_request: str
    image_path: str

    foreground_path: str
    mask_path: str

    product_analysis: Dict[str, Any]
    scene_plans: List[Dict[str, Any]]

    backgrounds: List[Dict[str, Any]]
    results: List[Dict[str, Any]]
    verifications: List[Dict[str, Any]]

    error: Optional[str]
    summary: Dict[str, Any]


class ImageRuntimeContext(TypedDict, total=False):
    """
    LangGraph runtime context schema.

    放本次运行配置，避免把配置项污染到 workflow state 里。
    """

    user_id: str
    request_id: str
    output_dir: str
    temp_dir: str
    scene_count: int
    size: str
    quality: str
    enable_verify: bool
