# -*- coding: utf-8 -*-
"""
dynamic_product_scene_graph.py

A LangGraph + LangChain Core + OpenAI Image API based tool class for generating
product usage-scene images from a single product image.

Key idea:
- LLM plans product category, scene list, and natural layout automatically.
- Code executes product segmentation, layout transform, and image composition.
- GPT Image generates only the scene/background; the product foreground is pasted back
  from the original image to reduce tool/hardware structure drift.

Install:
    pip install -U openai langgraph langchain-core pydantic pillow rembg

Usage:
    export OPENAI_API_KEY="..."

    from dynamic_product_scene_graph import DynamicProductSceneGraph

    tool = DynamicProductSceneGraph()
    state = tool.invoke(
        image_path="wrench.png",
        user_request="基于这张扳手商品原图，生成4张不同使用场景图，适合电商详情页。",
        scene_count=4,
        enable_verify=False,
    )
    print(state["summary"])
"""

from __future__ import annotations

import base64
import json
import os
import re
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Literal, Optional, TypedDict

from openai import OpenAI
from PIL import Image, ImageEnhance, ImageFilter
from pydantic import BaseModel, Field, ValidationError

from langchain_core.tools import tool as langchain_tool
from langgraph.graph import END, START, StateGraph
from langgraph.runtime import Runtime

try:
    from rembg import remove as rembg_remove
except Exception:  # pragma: no cover - handled at runtime
    rembg_remove = None


# =============================================================================
# 1) Schemas
# =============================================================================

ProductCategory = Literal[
    "tool",
    "hardware",
    "mechanical",
    "electronics",
    "home_goods",
    "kitchenware",
    "apparel",
    "soft_goods",
    "other",
]

PreserveLevel = Literal["pixel", "strict", "creative"]


class ProductAnalysis(BaseModel):
    """LLM analysis of the uploaded product image."""

    product_name: str = Field(description="商品名称，例如 adjustable wrench")
    category: ProductCategory = Field(description="商品类别")
    preserve_level: PreserveLevel = Field(description="保真等级")
    key_structure_points: List[str] = Field(default_factory=list, description="必须保持不变的结构点")
    risk_points: List[str] = Field(default_factory=list, description="容易被生成模型改错的区域")


class ScenePlan(BaseModel):
    """
    A dynamic scene + layout plan generated by the LLM.

    The user does NOT manually provide target_width_ratio / center ratios / rotation.
    The LLM decides them based on the product and scene.
    """

    name: str = Field(description="场景任务名，例如 workbench_repair_scene")
    scene_prompt: str = Field(description="用于生成背景场景的 prompt")
    usage_context: str = Field(description="商品在该场景中的自然出现方式")

    target_width_ratio: float = Field(description="商品目标宽度占画布宽度比例，建议 0.25~0.90")
    center_x_ratio: float = Field(description="商品中心点 x 比例，0~1")
    center_y_ratio: float = Field(description="商品中心点 y 比例，0~1")
    rotation_degrees: float = Field(description="商品旋转角度，工具类建议 -25~25 度")

    depth_layer: Literal["foreground", "midground", "background"] = "foreground"
    visual_role: Literal["hero", "primary", "supporting"] = "primary"
    shadow_strength: Literal["soft", "medium", "strong"] = "medium"
    preserve_level: PreserveLevel = "pixel"


class MultiScenePlan(BaseModel):
    product: ProductAnalysis
    scenes: List[ScenePlan]


class ImageWorkflowState(TypedDict, total=False):
    """
    LangGraph state schema.

    This is the shared state passed through graph nodes. It is not a global variable;
    it is the per-invocation workflow state.
    """

    user_request: str
    image_path: str

    foreground_path: str
    mask_path: str

    product_analysis: Dict[str, Any]
    scene_plans: List[Dict[str, Any]]

    backgrounds: List[Dict[str, Any]]
    results: List[Dict[str, Any]]
    verifications: List[Dict[str, Any]]

    error: Optional[str]
    summary: Dict[str, Any]


@dataclass
class ImageRuntimeContext:
    """
    LangGraph runtime context schema.

    Put per-run configuration here instead of polluting ImageWorkflowState.
    Workflow products/results still belong in state.
    """

    user_id: str = ""
    request_id: str = ""
    output_dir: str = "generated_images"
    temp_dir: str = "temp_product_assets"
    scene_count: int = 4
    size: str = "1024x1024"
    quality: str = "high"
    enable_verify: bool = False


# =============================================================================
# 2) Main tool class
# =============================================================================

class DynamicProductSceneGraph:
    """
    Final tool class.

    Input:
        A single product image, such as a wrench product photo.

    Output:
        Multiple usage-scene images where the product is automatically scaled,
        moved, and lightly rotated according to LLM scene planning.

    Design:
        LLM plans; code composes; GPT Image renders backgrounds.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        planner_model: str = "gpt-4.1",
        image_model: str = "gpt-image-2",
        output_dir: str = "generated_images",
        temp_dir: str = "temp_product_assets",
    ):
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        if not self.api_key:
            raise ValueError("请传入 api_key 或设置 OPENAI_API_KEY 环境变量。")

        self.client = OpenAI(api_key=self.api_key)
        self.planner_model = planner_model
        self.image_model = image_model
        self.output_dir = Path(output_dir)
        self.temp_dir = Path(temp_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.temp_dir.mkdir(parents=True, exist_ok=True)

        self.graph = self._build_graph()

    # ---------------------------------------------------------------------
    # Public entrypoint
    # ---------------------------------------------------------------------

    def invoke(
        self,
        image_path: str,
        user_request: str = "生成该商品在不同使用场景中的电商详情页图片。",
        scene_count: int = 4,
        size: str = "1024x1024",
        quality: str = "high",
        output_dir: Optional[str] = None,
        temp_dir: Optional[str] = None,
        enable_verify: bool = False,
        user_id: str = "",
        request_id: Optional[str] = None,
    ) -> ImageWorkflowState:
        """
        One-call workflow.

        The user only supplies the product image and natural-language requirement.
        Scale / position / rotation are decided by the LLM during planning.
        """
        image_path = str(image_path)
        if not Path(image_path).exists():
            raise FileNotFoundError(f"商品原图不存在：{image_path}")

        request_id = request_id or uuid.uuid4().hex

        init_state: ImageWorkflowState = {
            "user_request": user_request,
            "image_path": image_path,
            "backgrounds": [],
            "results": [],
            "verifications": [],
        }

        ctx = {
            "user_id": user_id,
            "request_id": request_id,
            "output_dir": output_dir or str(self.output_dir),
            "temp_dir": temp_dir or str(self.temp_dir),
            "scene_count": scene_count,
            "size": size,
            "quality": quality,
            "enable_verify": enable_verify,
        }

        return self.graph.invoke(init_state, context=ctx) # type: ignore

    def build_langchain_tools(self):
        """
        Optional LangChain Tool wrapper.

        Use this only if you later want to put this workflow behind an Agent/ToolNode.
        The current core flow is LangGraph custom nodes, not ToolNode.
        """
        graph_tool = self

        @langchain_tool
        def generate_product_usage_scenes(
            image_path: str,
            user_request: str = "生成该商品在不同使用场景中的电商详情页图片。",
            scene_count: int = 4,
        ) -> str:
            """Generate multiple product usage-scene images from one product image."""
            state = graph_tool.invoke(
                image_path=image_path,
                user_request=user_request,
                scene_count=scene_count,
            )
            return json.dumps(
                {
                    "summary": state.get("summary"),
                    "results": state.get("results", []),
                    "product_analysis": state.get("product_analysis"),
                },
                ensure_ascii=False,
            )

        return [generate_product_usage_scenes]

    # ---------------------------------------------------------------------
    # Graph build
    # ---------------------------------------------------------------------

    def _build_graph(self):
        builder = StateGraph(ImageWorkflowState, context_schema=ImageRuntimeContext) # type: ignore

        builder.add_node("segment_product", self._segment_product_node) # type: ignore
        builder.add_node("plan_scenes", self._plan_scenes_node) # type: ignore
        builder.add_node("generate_backgrounds", self._generate_backgrounds_node) # type: ignore
        builder.add_node("compose_results", self._compose_results_node) # type: ignore
        builder.add_node("verify_results", self._verify_results_node) # type: ignore
        builder.add_node("summarize", self._summarize_node) # type: ignore

        builder.add_edge(START, "segment_product")
        builder.add_edge("segment_product", "plan_scenes")
        builder.add_edge("plan_scenes", "generate_backgrounds")
        builder.add_edge("generate_backgrounds", "compose_results")
        builder.add_edge("compose_results", "verify_results")
        builder.add_edge("verify_results", "summarize")
        builder.add_edge("summarize", END)

        return builder.compile()

    # ---------------------------------------------------------------------
    # Runtime context helper
    # ---------------------------------------------------------------------

    @staticmethod
    def _ctx(runtime: Runtime[ImageRuntimeContext], key: str, default: Any = None) -> Any:
        ctx = getattr(runtime, "context", None)
        if ctx is None:
            return default
        if isinstance(ctx, dict):
            return ctx.get(key, default)
        return getattr(ctx, key, default)

    # ---------------------------------------------------------------------
    # Node 1: auto segmentation
    # ---------------------------------------------------------------------

    def _segment_product_node(
        self,
        state: ImageWorkflowState,
        runtime: Runtime[ImageRuntimeContext],
    ) -> ImageWorkflowState:
        try:
            if rembg_remove is None:
                raise ImportError("缺少 rembg。请执行：pip install rembg")

            image_path = state["image_path"]
            temp_dir = Path(self._ctx(runtime, "temp_dir", str(self.temp_dir)))
            temp_dir.mkdir(parents=True, exist_ok=True)

            stem = Path(image_path).stem
            foreground_path = str(temp_dir / f"{stem}_foreground_{uuid.uuid4().hex}.png")
            mask_path = str(temp_dir / f"{stem}_mask_{uuid.uuid4().hex}.png")

            with open(image_path, "rb") as f:
                input_bytes = f.read()

            output_bytes = rembg_remove(input_bytes)

            with open(foreground_path, "wb") as f:
                f.write(output_bytes)

            fg = Image.open(foreground_path).convert("RGBA")
            alpha = fg.getchannel("A")
            # White = product, black = background
            mask = alpha.point(lambda p: 255 if p > 10 else 0).convert("L")
            mask.save(mask_path)

            return {
                **state,
                "foreground_path": foreground_path,
                "mask_path": mask_path,
            }
        except Exception as e:
            return {**state, "error": f"segment_product 失败：{e}"}

    # ---------------------------------------------------------------------
    # Node 2: LLM product analysis + scene/layout planning
    # ---------------------------------------------------------------------

    def _plan_scenes_node(
        self,
        state: ImageWorkflowState,
        runtime: Runtime[ImageRuntimeContext],
    ) -> ImageWorkflowState:
        if state.get("error"):
            return state

        try:
            image_path = state["image_path"]
            scene_count = int(self._ctx(runtime, "scene_count", 4))
            user_request = state.get("user_request", "生成商品使用场景图。")

            plan = self._call_scene_planner(
                image_path=image_path,
                user_request=user_request,
                scene_count=scene_count,
            )

            # Safety clamp for generated numeric values.
            clean_scenes: List[Dict[str, Any]] = []
            for s in plan.scenes[:scene_count]:
                sd = s.model_dump()
                sd["target_width_ratio"] = self._clamp_float(sd.get("target_width_ratio"), 0.25, 0.90, 0.65)
                sd["center_x_ratio"] = self._clamp_float(sd.get("center_x_ratio"), 0.05, 0.95, 0.55)
                sd["center_y_ratio"] = self._clamp_float(sd.get("center_y_ratio"), 0.10, 0.92, 0.60)
                sd["rotation_degrees"] = self._clamp_float(sd.get("rotation_degrees"), -35, 35, 0)
                clean_scenes.append(sd)

            return {
                **state,
                "product_analysis": plan.product.model_dump(),
                "scene_plans": clean_scenes,
            }
        except Exception as e:
            # fallback prevents the whole workflow from collapsing if JSON planning fails
            fallback = self._fallback_tool_plan(scene_count=int(self._ctx(runtime, "scene_count", 4)))
            return {
                **state,
                "product_analysis": fallback.product.model_dump(),
                "scene_plans": [s.model_dump() for s in fallback.scenes],
                "error": None,
            }

    def _call_scene_planner(
        self,
        image_path: str,
        user_request: str,
        scene_count: int,
    ) -> MultiScenePlan:
        image_url = self._image_to_data_url(image_path)

        prompt = f"""
        你是电商商品场景图导演、商业摄影构图师、工具/五金类商品视觉质检专家。
        
        用户上传了一张商品原图。请你分析商品，并规划 {scene_count} 张不同使用场景图。
        
        用户需求：
        {user_request}
        
        核心目标：
        1. 生成不同使用场景，不是只换背景。
        2. 商品可以在不同场景中自然变大、变小、改变位置、轻微旋转。
        3. 用户不会手动指定缩放、位置、角度；这些由你根据场景自动规划。
        4. 如果商品是工具、五金、机械、电子配件，必须选择 pixel 或 strict 保真策略。
        5. 场景优先做“电商可控的轻使用场景/上下文使用场景”，不要强行规划复杂手握、遮挡、精密接触动作。
        6. 背景 prompt 必须要求：不要生成同款主商品；要留出自然空间用于后期贴入商品。
        7. target_width_ratio 取 0.25~0.90；工具类通常 0.45~0.80。
        8. center_x_ratio / center_y_ratio 取 0~1。
        9. rotation_degrees 工具类建议 -25~25，必要时可到 -35~35。
        10. 场景要真实、商业摄影、电商详情页/广告可用。
        
        请严格输出 JSON，不要解释，不要 Markdown。格式：
        {{
          "product": {{
            "product_name": "adjustable wrench",
            "category": "tool",
            "preserve_level": "pixel",
            "key_structure_points": ["adjustable jaw", "worm gear", "handle hole", "metal outline"],
            "risk_points": ["jaw shape may change", "worm gear may disappear", "handle hole may change"]
          }},
          "scenes": [
            {{
              "name": "workbench_repair_scene",
              "scene_prompt": "A realistic wooden workbench repair scene with screws, bolts, and wood pieces nearby, warm workshop lighting, an empty open area reserved for placing the main product in the foreground, no adjustable wrench or duplicate main tool in the background, commercial ecommerce photography",
              "usage_context": "The product appears as the main repair tool near fasteners on a workbench.",
              "target_width_ratio": 0.68,
              "center_x_ratio": 0.58,
              "center_y_ratio": 0.62,
              "rotation_degrees": -12,
              "depth_layer": "foreground",
              "visual_role": "primary",
              "shadow_strength": "medium",
              "preserve_level": "pixel"
            }}
          ]
        }}
        """.strip()

        response = self.client.responses.create(
            model=self.planner_model,
            input=[ # type: ignore
                {
                    "role": "user",
                    "content": [
                        {"type": "input_text", "text": prompt},
                        {"type": "input_image", "image_url": image_url},
                    ],
                }
            ],
        )

        data = self._extract_json(response.output_text)
        return MultiScenePlan(**data)

    # ---------------------------------------------------------------------
    # Node 3: background generation
    # ---------------------------------------------------------------------

    def _generate_backgrounds_node(
        self,
        state: ImageWorkflowState,
        runtime: Runtime[ImageRuntimeContext],
    ) -> ImageWorkflowState:
        if state.get("error"):
            return state

        output_dir = Path(self._ctx(runtime, "output_dir", str(self.output_dir)))
        output_dir.mkdir(parents=True, exist_ok=True)
        size = self._ctx(runtime, "size", "1024x1024")
        quality = self._ctx(runtime, "quality", "high")

        backgrounds: List[Dict[str, Any]] = []
        for idx, scene in enumerate(state.get("scene_plans", []), start=1):
            try:
                scene_name = scene.get("name", f"scene_{idx}")
                bg_path = str(output_dir / f"bg_{scene_name}_{uuid.uuid4().hex}.png")

                # Give the background model a layout hint to reserve space.
                layout_hint = (
                    f"Reserve a natural open placement area around normalized center "
                    f"({scene.get('center_x_ratio')}, {scene.get('center_y_ratio')}) "
                    f"with approximate product width ratio {scene.get('target_width_ratio')}."
                )

                prompt = f"""
                Create a realistic commercial product usage-scene background.
                
                Scene requirement:
                {scene.get('scene_prompt', '')}
                
                Layout hint:
                {layout_hint}
                
                Important rules:
                - Do NOT generate the main product itself.
                - Do NOT generate an adjustable wrench, duplicate same product, or similar hero tool in the reserved area.
                - Background can include contextual objects such as bolts, pipes, wood, workshop benches, bicycle parts, garage elements, or industrial surfaces, if appropriate.
                - Leave a believable empty area where the actual product foreground will be composited later.
                - Make lighting, surface, and perspective realistic for ecommerce photography.
                - No text, no watermark, no logo.
                """.strip()

                res = self.client.images.generate(
                    model=self.image_model,
                    prompt=prompt,
                    size=size,
                    quality=quality,
                    n=1,
                )
                self._save_b64_image(res.data[0].b64_json, bg_path)

                backgrounds.append(
                    {
                        "scene_name": scene_name,
                        "background_path": bg_path,
                        "prompt": prompt,
                    }
                )
            except Exception as e:
                backgrounds.append(
                    {
                        "scene_name": scene.get("name", f"scene_{idx}"),
                        "success": False,
                        "error": str(e),
                    }
                )

        return {**state, "backgrounds": backgrounds}

    # ---------------------------------------------------------------------
    # Node 4: compose foreground into generated backgrounds
    # ---------------------------------------------------------------------

    def _compose_results_node(
        self,
        state: ImageWorkflowState,
        runtime: Runtime[ImageRuntimeContext],
    ) -> ImageWorkflowState:
        if state.get("error"):
            return state

        output_dir = Path(self._ctx(runtime, "output_dir", str(self.output_dir)))
        output_dir.mkdir(parents=True, exist_ok=True)

        foreground_path = state.get("foreground_path")
        if not foreground_path:
            return {**state, "error": "缺少 foreground_path，无法合成商品。"}

        scene_plans = state.get("scene_plans", [])
        backgrounds = state.get("backgrounds", [])
        results: List[Dict[str, Any]] = []

        for scene, bg in zip(scene_plans, backgrounds):
            scene_name = scene.get("name", "scene")
            try:
                if not bg.get("background_path"):
                    raise ValueError(bg.get("error", "背景生成失败"))

                output_path = str(output_dir / f"final_{scene_name}_{uuid.uuid4().hex}.png")
                composed_path = self._compose_product_by_plan(
                    background_path=bg["background_path"],
                    foreground_path=foreground_path,
                    scene=scene,
                    output_path=output_path,
                )
                results.append(
                    {
                        "success": True,
                        "scene_name": scene_name,
                        "image_path": composed_path,
                        "background_path": bg["background_path"],
                        "layout": {
                            "target_width_ratio": scene.get("target_width_ratio"),
                            "center_x_ratio": scene.get("center_x_ratio"),
                            "center_y_ratio": scene.get("center_y_ratio"),
                            "rotation_degrees": scene.get("rotation_degrees"),
                            "depth_layer": scene.get("depth_layer"),
                            "visual_role": scene.get("visual_role"),
                            "shadow_strength": scene.get("shadow_strength"),
                        },
                        "scene_prompt": scene.get("scene_prompt"),
                        "usage_context": scene.get("usage_context"),
                    }
                )
            except Exception as e:
                results.append(
                    {
                        "success": False,
                        "scene_name": scene_name,
                        "error": str(e),
                    }
                )

        return {**state, "results": results}

    def _compose_product_by_plan(
        self,
        background_path: str,
        foreground_path: str,
        scene: Dict[str, Any],
        output_path: str,
    ) -> str:
        bg = Image.open(background_path).convert("RGBA")
        fg = Image.open(foreground_path).convert("RGBA")
        fg = self._trim_transparent_padding(fg)

        bg_w, bg_h = bg.size
        fg_w, fg_h = fg.size

        target_width_ratio = self._clamp_float(scene.get("target_width_ratio"), 0.20, 0.90, 0.65)
        target_w = max(1, int(bg_w * target_width_ratio))
        scale = target_w / max(fg_w, 1)
        target_h = max(1, int(fg_h * scale))
        fg = fg.resize((target_w, target_h), Image.Resampling.LANCZOS)

        rotation = self._clamp_float(scene.get("rotation_degrees"), -35, 35, 0)
        fg = fg.rotate(rotation, expand=True, resample=Image.Resampling.BICUBIC)

        center_x_ratio = self._clamp_float(scene.get("center_x_ratio"), 0.0, 1.0, 0.5)
        center_y_ratio = self._clamp_float(scene.get("center_y_ratio"), 0.0, 1.0, 0.6)
        center_x = int(bg_w * center_x_ratio)
        center_y = int(bg_h * center_y_ratio)

        x = center_x - fg.width // 2
        y = center_y - fg.height // 2

        # Keep at least part of the product inside the frame.
        x = max(-fg.width // 3, min(x, bg_w - fg.width * 2 // 3))
        y = max(-fg.height // 3, min(y, bg_h - fg.height * 2 // 3))

        composed = self._add_shadow(
            canvas=bg,
            product_layer=fg,
            x=x,
            y=y,
            shadow_strength=scene.get("shadow_strength", "medium"),
        )
        composed.paste(fg, (x, y), fg)

        # Whole-image mild finishing. This changes tonality slightly, not product geometry.
        composed = self._light_finish(composed)
        composed.save(output_path)
        return output_path

    # ---------------------------------------------------------------------
    # Node 5: optional visual verification
    # ---------------------------------------------------------------------

    def _verify_results_node(
        self,
        state: ImageWorkflowState,
        runtime: Runtime[ImageRuntimeContext],
    ) -> ImageWorkflowState:
        if state.get("error"):
            return state

        enable_verify = bool(self._ctx(runtime, "enable_verify", False))
        if not enable_verify:
            return {**state, "verifications": []}

        verifications: List[Dict[str, Any]] = []
        source = state.get("image_path")
        for result in state.get("results", []):
            if not result.get("success") or not result.get("image_path"):
                continue
            try:
                check = self._verify_product_consistency(
                    original_image_path=source,
                    final_image_path=result["image_path"],
                )
                result["verification"] = check
                verifications.append({"scene_name": result.get("scene_name"), "verification": check})
            except Exception as e:
                verifications.append({"scene_name": result.get("scene_name"), "error": str(e)})

        return {**state, "verifications": verifications, "results": state.get("results", [])}

    def _verify_product_consistency(self, original_image_path: str, final_image_path: str) -> Dict[str, Any]:
        prompt = """
        Compare the product in the original image with the product composited in the final scene image.
        Focus on tool/hardware structural consistency: jaw shape, holes, handles, metal outline, visible parts, and whether it became a different tool.
        Return strict JSON only:
        {
          "is_same_product": true,
          "structure_score": 0.0,
          "issues": ["..."]
        }
        Use structure_score from 0 to 1, where 1 means the product structure is highly consistent.
        """.strip()

        response = self.client.responses.create(
            model=self.planner_model,
            input=[ # type: ignore
                {
                    "role": "user",
                    "content": [
                        {"type": "input_text", "text": prompt},
                        {"type": "input_image", "image_url": self._image_to_data_url(original_image_path)},
                        {"type": "input_image", "image_url": self._image_to_data_url(final_image_path)},
                    ],
                }
            ],
        )
        try:
            return self._extract_json(response.output_text)
        except Exception:
            return {"raw": response.output_text}

    # ---------------------------------------------------------------------
    # Node 6: summarize
    # ---------------------------------------------------------------------

    def _summarize_node(self, state: ImageWorkflowState) -> ImageWorkflowState:
        results = state.get("results", [])
        success_items = [r for r in results if r.get("success")]

        summary = {
            "success_count": len(success_items),
            "total": len(results),
            "image_paths": [r.get("image_path") for r in success_items if r.get("image_path")],
            "foreground_path": state.get("foreground_path"),
            "mask_path": state.get("mask_path"),
            "error": state.get("error"),
        }
        return {**state, "summary": summary}

    # ---------------------------------------------------------------------
    # Utility methods
    # ---------------------------------------------------------------------

    @staticmethod
    def _clamp_float(value: Any, low: float, high: float, default: float) -> float:
        try:
            v = float(value)
        except Exception:
            v = default
        return max(low, min(v, high))

    @staticmethod
    def _extract_json(text: str) -> Dict[str, Any]:
        text = (text or "").strip()
        text = re.sub(r"^```(?:json)?", "", text).strip()
        text = re.sub(r"```$", "", text).strip()
        start = text.find("{")
        end = text.rfind("}")
        if start >= 0 and end >= 0:
            text = text[start : end + 1]
        return json.loads(text)

    @staticmethod
    def _trim_transparent_padding(image: Image.Image) -> Image.Image:
        image = image.convert("RGBA")
        alpha = image.getchannel("A")
        bbox = alpha.getbbox()
        return image.crop(bbox) if bbox else image

    @staticmethod
    def _light_finish(image: Image.Image) -> Image.Image:
        rgb = image.convert("RGB")
        rgb = ImageEnhance.Contrast(rgb).enhance(1.03)
        rgb = ImageEnhance.Sharpness(rgb).enhance(1.02)
        return rgb.convert("RGBA")

    @staticmethod
    def _add_shadow(
        canvas: Image.Image,
        product_layer: Image.Image,
        x: int,
        y: int,
        shadow_strength: str = "medium",
    ) -> Image.Image:
        if shadow_strength == "soft":
            opacity, blur, offset = 65, 18, (8, 10)
        elif shadow_strength == "strong":
            opacity, blur, offset = 130, 26, (16, 20)
        else:
            opacity, blur, offset = 95, 22, (12, 15)

        alpha = product_layer.getchannel("A")
        shadow = Image.new("RGBA", product_layer.size, (0, 0, 0, opacity))
        shadow.putalpha(alpha)
        shadow = shadow.filter(ImageFilter.GaussianBlur(blur))

        shadow_canvas = Image.new("RGBA", canvas.size, (0, 0, 0, 0))
        shadow_canvas.paste(shadow, (x + offset[0], y + offset[1]), shadow)
        return Image.alpha_composite(canvas, shadow_canvas)

    @staticmethod
    def _image_to_data_url(image_path: str) -> str:
        ext = Path(image_path).suffix.lower().replace(".", "")
        if ext == "jpg":
            ext = "jpeg"
        if ext not in {"png", "jpeg", "webp"}:
            ext = "png"
        with open(image_path, "rb") as f:
            b64 = base64.b64encode(f.read()).decode("utf-8")
        return f"data:image/{ext};base64,{b64}"

    @staticmethod
    def _save_b64_image(b64_json: str, output_path: str) -> str:
        Path(output_path).write_bytes(base64.b64decode(b64_json))
        return output_path

    @staticmethod
    def _fallback_tool_plan(scene_count: int = 4) -> MultiScenePlan:
        """Fallback plan when LLM JSON planning fails."""
        product = ProductAnalysis(
            product_name="tool product",
            category="tool",
            preserve_level="pixel",
            key_structure_points=["tool outline", "functional head", "handle", "visible holes or adjustment parts"],
            risk_points=["tool may be transformed into another tool", "functional head may change"],
        )
        scenes = [
            ScenePlan(
                name="workbench_repair_scene",
                scene_prompt="A realistic wooden workbench repair scene with bolts, nuts, wood pieces, warm workshop lighting, an empty area reserved for the main product in the foreground, no duplicate hero tool, ecommerce photography",
                usage_context="The tool appears as the main repair tool on a workbench.",
                target_width_ratio=0.68,
                center_x_ratio=0.58,
                center_y_ratio=0.63,
                rotation_degrees=-12,
                depth_layer="foreground",
                visual_role="primary",
                shadow_strength="medium",
                preserve_level="pixel",
            ),
            ScenePlan(
                name="plumbing_repair_scene",
                scene_prompt="A realistic plumbing repair scene near metal pipes and fittings, clean workshop or utility room surface, an empty space reserved for placing the main product, no duplicate hero tool, commercial lighting",
                usage_context="The tool is placed near pipe fittings as if ready for tightening.",
                target_width_ratio=0.55,
                center_x_ratio=0.42,
                center_y_ratio=0.66,
                rotation_degrees=10,
                depth_layer="foreground",
                visual_role="primary",
                shadow_strength="medium",
                preserve_level="pixel",
            ),
            ScenePlan(
                name="garage_automotive_scene",
                scene_prompt="A realistic automotive garage repair scene with engine parts, metal surface, subtle oil-free clean commercial styling, an empty foreground area for the main product, no duplicate hero tool",
                usage_context="The tool appears on a garage work surface near automotive parts.",
                target_width_ratio=0.48,
                center_x_ratio=0.68,
                center_y_ratio=0.58,
                rotation_degrees=-8,
                depth_layer="midground",
                visual_role="primary",
                shadow_strength="strong",
                preserve_level="pixel",
            ),
            ScenePlan(
                name="bicycle_repair_scene",
                scene_prompt="A realistic bicycle maintenance scene near a bike wheel axle and small fasteners, clean home garage background, an empty area reserved for placing the main product, no duplicate hero tool, ecommerce photography",
                usage_context="The tool is placed near a bicycle repair area.",
                target_width_ratio=0.52,
                center_x_ratio=0.50,
                center_y_ratio=0.70,
                rotation_degrees=15,
                depth_layer="foreground",
                visual_role="primary",
                shadow_strength="soft",
                preserve_level="pixel",
            ),
        ]
        return MultiScenePlan(product=product, scenes=scenes[:scene_count])


if __name__ == "__main__":
    # Example:
    # python dynamic_product_scene_graph.py wrench.png
    import sys

    if len(sys.argv) < 2:
        print("Usage: python dynamic_product_scene_graph.py <product_image_path>")
        raise SystemExit(1)

    graph_tool = DynamicProductSceneGraph()
    final_state = graph_tool.invoke(
        image_path=sys.argv[1],
        user_request="基于这张工具/五金商品原图，生成4张不同使用场景图，适合电商详情页。商品可以随场景自然变大、变小、改变位置、轻微旋转，但商品结构必须尽量保持原图一致。",
        scene_count=4,
        enable_verify=False,
    )
    print(json.dumps(final_state.get("summary", {}), ensure_ascii=False, indent=2))
